#!/bin/bash
#set -e;

db_image="jeffutter/postgresql"
home=$(cat HOME)

if [[ -n "$(docker ps -a | grep $db_image)" ]]; then
  docker rm $(docker stop $(docker ps -a | grep $db_image | awk '{print $1}'))
fi

if [[ -n "$(docker images | grep $db_image)" ]]; then
  docker rmi -f $(docker images | grep $db_image | awk '{print $1}')
fi

rm -rf $home
